kind: BuildConfig
apiVersion: v1
metadata:
  name: "reversi-bc"
  namespace: "robot-games-namespace-001"
spec:
  triggers: []
  runPolicy: Serial
  source:
    type: Dockerfile
    dockerfile: FROM cddirector/sampleapp
  strategy:
    type: Docker
    dockerStrategy:
      noCache: true
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: "reversi:latest"
  resources: {}
  postCommit: {}
  nodeSelector: {}
status:
  lastVersion: 
