kind: Service
apiVersion: v1
metadata:
  name: "reversi"
  namespace: "manual-build-config"
  creationTimestamp:
  labels:
    app: "reversi"
spec:
  selector:
    app: "reversi"
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: reversi
  namespace: manual-build-config
  labels:
    app: "reversi"
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 2400
    resources: {}
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "reversi"
        from:
          kind: ImageStreamTag
          name: "ImageStream_reversi:latest"
    - type: ConfigChange`
  replicas: 1
  selector:
  template:
    metadata:
      creationTimestamp:
      labels:
        app: "reversi"
      annotations:
    spec:
      containers:
      - name: "reversi"
        image: "cddirector/sampleapp:latest"
        resources:
          limits:
            cpu: 120m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
