kind: Service
apiVersion: v1
metadata:
  name: "reversi"
  namespace: "manual-build-config"
  creationTimestamp:
  labels:
    app: "reversi"
spec:
  selector:
    app: "reversi"
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080  
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: reversi
  namespace: manual-build-config
  labels:
    app: "reversi"
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 2400
    resources: {}
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "reversi"
        from:
          kind: ImageStreamTag
          name: "reversi:latest"
    - type: ConfigChange`
  replicas: 1
  selector:
  template:
    metadata:
      creationTimestamp:
      labels:
        app: "reversi"
      annotations:
    spec:
      containers:
      - name: "reversi"
        image: "cddirector/sampleapp:latest"
        resources:
          limits:
            cpu: 120m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 8080
          protocol: TCP            
        imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - curl
                - '-f'
                - 'http://localhost:8080/cdd'
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10        
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
